import mongoose, { Schema, Document, Model } from "mongoose";

// 1. Define the TypeScript Interface
export interface IBriefing extends Document {
  createdByOfficerId: mongoose.Types.ObjectId; // Links to your User/Staff model
  post: string;
  shift: "Morning" | "Afternoon" | "Night"; //
  language: "English" | "Tamil" | "Hindi"; //
  dutyDate: Date; // The specific day this briefing applies to

  // The actual text generated by Claude
  briefingScript: string; // [cite: 79]

  createdAt: Date;
  updatedAt: Date;
}

// 2. Define the Mongoose Schema
const BriefingSchema: Schema<IBriefing> = new Schema(
  {
    createdByOfficerId: {
      type: Schema.Types.ObjectId,
      ref: "Officer", // Adjust this if your user collection is named differently
      required: true,
    },
    post: {
      type: String,
      required: true,
    },
    shift: {
      type: String,
      enum: ["Morning", "Afternoon", "Night"], //
      required: true,
    },
    // language: {
    //   type: String,
    //   enum: ["English", "Tamil", "Hindi"], //
    //   required: true,
    // },
    dutyDate: {
      type: Date,
      required: true,
      default: Date.now,
    },
    briefingScript: {
      type: String,
      required: true,
    },
  },
  { timestamps: true },
);

// 3. Export the model safely for Next.js hot-reloading
const Briefing: Model<IBriefing> =
  mongoose.models.Briefing ||
  mongoose.model<IBriefing>("Briefing", BriefingSchema);

export default Briefing;
